<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-B2220QC" ignored="1" name="Test(failed)" tests="1" failures="1" timestamp="2022-05-20T10:13:54 IST" time="0.212" errors="0">
  <testcase name="testB" time="0.024" classname="tests.TestClass2">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.fail(Assert.java:95)
at tests.TestClass2.testB(TestClass2.java:32)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testB -->
  <testcase name="testA" time="0.0" classname="tests.TestClass2">
    <ignored/>
  </testcase> <!-- testA -->
</testsuite> <!-- Test(failed) -->
